---
title: "Appending Datasets"
subtitle: "GSE S580"
author: "Emory Rapaport, Kim Her, Nicholas Feng Schaefer"
output: html_notebook
---

# Set Up
```{r, message=FALSE}
library(tidyverse)
library(readxl)
library(lubridate)
library(openxlsx)
```

# Loading Datasets
```{r}
greenwheel <- read_xlsx("/Users/nicholas/Desktop/Cal_Poly_SLO/5-World_Bank/Data/merged_data/gw_filtered.xlsx")
just_driver <- read_xlsx("/Users/nicholas/Desktop/Cal_Poly_SLO/5-World_Bank/Data/merged_data/ice_filtered.xlsx")
```

# Pre Sanity Checks

## Identification Variable
```{r}
greenwheel$greenwheel_dummy <- 1
just_driver$greenwheel_dummy <- 0
```

## Column Names
```{r}
if (identical(colnames(greenwheel), colnames(just_driver)) == TRUE){
    print("The column names of both datasets are the same.")
} else{
    print("The column names of the datasets don't match")
}
```

```{r}
setdiff(colnames(greenwheel), colnames(just_driver))
```

```{r}
setdiff(colnames(just_driver), colnames(greenwheel))
```

## Renaming Columns
```{r}
greenwheel <- greenwheel %>% 
    rename(educ = edu,
           daily_income_boda = salary,
           content = flex,
           start_pre = start_x,
           end_pre = end_x,
           start_daily = start_y,
           end_daily = end_y,
           time_work_prop = time_work_sample) %>% 
    dplyr::select(-far_home, -unsafe, -price_dist, -card, -other_income_1)

just_driver <- just_driver %>% 
    rename(educ = edc,
           other_income = income_other,
           other_income_1 = income_other_1,
           daily_income_boda = income_boda,
           start_pre = start,
           end_pre = end,
           time_work_prop = time_work_sample) %>% 
    select(-less_hr, -other_income_1)
```

```{r}
setdiff(colnames(greenwheel), colnames(just_driver))
```

```{r}
setdiff(colnames(just_driver), colnames(greenwheel))
```

```{r}
greenwheel$reject_other <- as.integer(greenwheel$reject_other)
just_driver$reject_other <- as.integer(just_driver$reject_other)
```

```{r}
just_driver$start_pre <- with_tz(ymd_hms(just_driver$start_pre), "UTC")
just_driver$end_pre <- with_tz(ymd_hms(just_driver$end_pre), "UTC")
```

## Number of Columns
```{r}
cat("The appended dataset should have", nrow(greenwheel) + nrow(just_driver), "rows.")
```

# Appending Datasets
```{r}
appended_df <- bind_rows(just_driver, greenwheel)

if (nrow(appended_df) == nrow(greenwheel) + nrow(just_driver)){
    print("The appending was successful!")
} else{
    print("Something went wrong.")
}
```

# Label Encoding The Columns
```{r, eval=FALSE}
appended_df <- appended_df %>% 
    mutate(gender = ifelse(gender == "Male", 1, 0),
           head = ifelse(head == "Yes, I am the head of the household", 1, 0),
           mar = case_when(
               mar == "No, I have never been married" ~ 0,
               mar == "Yes, I am currently married and living together" ~ 1,
               mar == "No, I have never been married" ~ 2
           ),
           educ = case_when(
               educ == "Did not complete primary" ~ 0,
               educ == "Primary" ~ 1,
               educ == "Secondary (Form 4)" ~ 2,
               educ == "Tertiary (university or certificate)" ~ 3
           ),
           )
```

```{r}
write.xlsx(appended_df, file = "/Users/nicholas/Desktop/Cal_Poly_SLO/5-World_Bank/Data/merged_data/appended_df.xlsx")
```





