---
title: "Matching Model"
author: "Kim Her"
date: "`r Sys.Date()`"
output: html_document
---

# Set Up
```{r, message=FALSE}
library(tidyverse)
library(Matching)
library(readxl)
```

# Loading Dataset
```{r, message=FALSE}
df <- read_xlsx('/Users/nicholas/Desktop/Cal_Poly_SLO/5-World_Bank/Data/merged_data/appended_df.xlsx')
```

```{r}
df <- df[!is.na(df$disposable_income) &
         !is.na(df$greenwheel_dummy) &
         !is.na(df$age) &
         !is.na(df$dep) &
         !is.na(df$leisure) &
         !is.na(df$educ) &
         !is.na(df$acc_med) &
         !is.na(df$insure), ]
```

# Matching

## Matching on Age and Education
```{r}
df1 <- df[!is.na(df$age) &
         !is.na(df$educ), ]
```

```{r}
matching_mod1 <- Match(Y = df1$disposable_income,
                       Tr = df1$greenwheel_dummy,
                       X = df1[,c("age", "educ")],
                       M = 1,
                       estimand = "ATE")

summary(matching_mod1)
```

## Matching Using More Covariates
```{r}
df2 <- df[!is.na(df$disposable_income) &
         !is.na(df$greenwheel_dummy) &
         !is.na(df$age) &
         !is.na(df$dep) &
         !is.na(df$leisure) &
         !is.na(df$educ) &
         !is.na(df$acc_med) &
         !is.na(df$insure), ]
```

```{r}
covariates <- df2 %>% 
    dplyr::select(age, educ, insure, acc_med, dep, leisure)

matching_mod2 <- Match(Y = df2$disposable_income,
                       Tr = df2$greenwheel_dummy,
                       X = covariates,
                       M = 1,
                       estimand = "ATE")

summary(matching_mod2)
```

## Matching On P-Scores
```{r}
logit_mod1 <- glm(greenwheel_dummy ~ age + educ + insure + acc_med + dep + leisure, data = df2, family = binomial(link = "logit"))
summary(logit_mod1)
```

```{r}
p_score <- predict(logit_mod1, newdata = df2, type = "response")

df2 <- cbind(df2, p_score)
```

```{r}
matching_mod3 <- Match(Y = df2$disposable_income,
                       Tr = df2$greenwheel_dummy,
                       X = df2$p_score,
                       M = 1,
                       estimand = "ATE")

summary(matching_mod3)
```